dist:     focal
sudo:     required  # используем Virtual Machine (а не Docker container)

language: c

compiler:
  - gcc

install:
  - sudo apt-get install valgrind
  - sudo pip3 install cpplint
  - sudo apt install cppcheck

script:
  - cpplint --extensions=c include/*/* src/*
  - cpplint --extensions=cpp test/*.cpp
  - cppcheck --inconclusive --enable=all --language=c src/*.c
  - mkdir cmake-build-debug && cd cmake-build-debug
  - cmake ..
  - make clean && make
  - valgrind --tool=memcheck --leak-check=full ./test/test_tests

after_success:
  - bash <(curl -s https://codecov.io/bash)